version: "3.9"
services:
  nginx:
    image: "nginx:latest"
    container_name: nginx
    environment:
      - TZ=Europe/Moscow
    ports:
      - "80:80"
    volumes: 
      - ./conf:/etc/nginx/conf.d
    depends_on:
      - flask

  flask:
    image: "aquaman/flask:1.0"
    container_name: flask
    environment:
      - TZ=Europe/Moscow
      - FLASK_DEBUG=True
      - PYTHONUNBUFFERED=True
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    command: sh -c "pip install -r requirements.txt && python app.py"
    depends_on:
      - postgres

  postgres:
    image: "postgres:15.0-alpine"
    container_name: postgres
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_PASSWORD=Passw0rd!
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
